### ISSUE TITLE
[BUG] Railcraft Conflict?

### ISSUE THREAD

**Issue by Phonavis** [hypherionmc/hyperlighting_public#4] opened 2020-08-06 03:47 UTC
**Describe the bug**
Place anything from the mod down with railcraft and it'll instantly CTD. Unsure if it's railcraft or this mod, but i'll post here first since a quick skim didn't find anything related to this on their git.

**System (please complete the following information):**
 - OS: Win 10
 - Java Version: 1.8.0_241
 - Minecraft Version: 1.12.2
 - Forge Version: 14.23.5.2854
 - Hyperlighting Ver 1.12.2_1.2
- Railcraft Version 12.0.0

**Crash Report*
   https://pastebin.com/ySGrU3ag

**Comment by hypherionmc** [comment] 2020-08-06 06:47
Hi and thanks for reporting this. This is kinda a known issue with a couple of mods now, but it's something I've never been able to reproduce reliably to find the cause/fix it. 

Known mods:
Buildcraft
Better Builders Wands

I will do some testing to see if I can recreate this issue

**Comment by hypherionmc** [comment] 2020-08-06 12:42
Okay this is a confirmed bug now. I will get to fixing it as soon as possible. It will be released in a dev build, until the next stable release

**Comment by hypherionmc** [comment] 2020-08-08 14:12
@Scarlet-Phonavis Would you mind giving this build a go to see if you still experience this issue?

https://ci.hypherionmc.me/job/Hyper-Lighting/job/1.12.2/14/artifact/build/libs/HyperLighting-dev-14.jar

**Comment by hypherionmc** [comment] 2020-08-12 10:37
Marking this as resolved for now. If you still experience this issue, please reopen this again

**Closed as completed by hypherionmc** 2020-08-12 10:37 UTC
Labels: bug in other software, fixed in dev
